### ISSUE TITLE
I would like to talk with you about the official Mackerel Terraform Provider

### ISSUE THREAD

**Issue by a-know** [xcezx/terraform-provider-mackerel#25]
Hi! I am @a-know, a member of the Mackerel staff (mackerel.io).
First off, thank you for making a wonderful OSS product!

We are currently creating an official Mackerel Terraform Provider starting with Mackerel Labs https://github.com/mackerelio-labs.
We would like to invite you to become a Contributor.

If this sounds like something you might be interested in, please join the Mackerel User Group (https://mackerel-ug-slackin.herokuapp.com/) on Slack.
Then I will invite you to the appropriate channel.

Thank you for your consideration. I look forward to your reply! :)

**Comment by xcezx** [comment]
Hi @a-know, I apologize for the delay in replying and thank you for your invitation to a contributor.

> We are currently creating an official Mackerel Terraform Provider starting with Mackerel Labs

Sounds good 👍 
I would like to help if there is something I can cooperate with.

**Comment by xcezx** [comment]
I just joined the slack.

**Comment by a-know** [comment]
Thank you!!
